"""Create models

Revision ID: 0ce13e67f642
Revises: 
Create Date: 2021-09-08 08:22:02.550493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ce13e67f642'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    marca = op.create_table('marca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marca_id'), 'marca', ['id'], unique=False)

    op.bulk_insert(marca, [{"marca": "AGRALE", "value": "102"},
                           {"marca": "BEPOBUS", "value": "206"},
                           {"marca": "CHEVROLET", "value": "103"},
                           {"marca": "CICCOBUS", "value": "121"},
                           {"marca": "DAF", "value": "197"},
                           {"marca": "EFFA-JMC", "value": "179"},
                           {"marca": "FIAT", "value": "104"},
                           {"marca": "FORD", "value": "105"},
                           {"marca": "FOTON", "value": "191"},
                           {"marca": "GMC", "value": "106"},
                           {"marca": "HYUNDAI", "value": "181"},
                           {"marca": "IVECO", "value": "122"},
                           {"marca": "JAC", "value": "188"},
                           {"marca": "MAN", "value": "184"},
                           {"marca": "MARCOPOLO", "value": "108"},
                           {"marca": "MASCARELLO", "value": "196"},
                           {"marca": "MAXIBUS", "value": "194"},
                           {"marca": "MERCEDES-BENZ", "value": "109"},
                           {"marca": "NAVISTAR", "value": "110"},
                           {"marca": "NEOBUS", "value": "111"},
                           {"marca": "PUMA-ALFA", "value": "112"},
                           {"marca": "SAAB-SCANIA", "value": "113"},
                           {"marca": "SCANIA", "value": "114"},
                           {"marca": "SHACMAN", "value": "193"},
                           {"marca": "SINOTRUK", "value": "166"},
                           {"marca": "VOLKSWAGEN", "value": "115"},
                           {"marca": "VOLVO", "value": "116"},
                           {"marca": "WALKBUS", "value": "144"}])
    
    op.create_table('veiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('veiculo', sa.String(), nullable=True),
    sa.Column('marca_id', sa.Integer(), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('vendido', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['marca_id'], ['marca.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_veiculo_id'), 'veiculo', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_veiculo_id'), table_name='veiculo')
    op.drop_table('veiculo')
    op.drop_index(op.f('ix_marca_id'), table_name='marca')
    op.drop_table('marca')
    # ### end Alembic commands ###
